version: '3.8'
services:
  mongo:
    image: mongo
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb+srv://mongo_admin:uAHb6bisRpTR9wqc@sc-mongo.tgixx.mongodb.net/?retryWrites=true&w=majority&appName=sc-mongo
    links:
     - mongo
    depends_on:
     - mongo
