name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SERVICE_NAME: ${github.repository}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print and Set variables
        shell: bash
        run: |
          set -x
          # Variables
          echo $DOCKER_USERNAME
          echo $SERVICE_NAME

      - name: Set up Docker Buildx #Setup Buildx for caching
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push $SERVICE_NAME-be
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-be
          push: true
          tags: $DOCKER_USERNAME/$SERVICE_NAME-be:latest

      - name: Build and push $SERVICE_NAME-fe
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-fe
          push: true
          tags: $DOCKER_USERNAME/$SERVICE_NAME-fe:latest

      - name: Log out from Docker Hub
        run: docker logout