name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'The image tag to deploy default to latest'
        required: false
        default: 'latest'
env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  ENVIROMENT: production
  HOSTNAME: es-devops.example.com
  IMAGE_TAG: latest # Overwrite later

jobs:
  rollback:
    runs-on: shared-github-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print and Set variables
        run: |
          set -x
          # Variables
          echo $SERVICE_NAME
          echo "IMAGE_TAG=${{ github.event.inputs.IMAGE_TAG }}" >> $GITHUB_ENV
          echo "NAMESPACE=$ENVIROMENT" >> $GITHUB_ENV
          echo "DOCKER_REPO=ghcr.io/${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "GITHUB_USER=${{ github.actor }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
          
      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Rollback to ${{ github.event.inputs.IMAGE_TAG }}
        shell: bash
        run: |
          bash deploy.sh