name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'The image tag to deploy default to latest'
        required: false
        default: 'latest'

jobs:
  rollback:
    runs-on: shared-github-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "IMAGE_TAG=${{ github.event.inputs.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Rollback to ${{ github.event.inputs.IMAGE_TAG }}
        shell: bash
        run: |
          bash deploy.sh