name: Test
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
jobs:
  greet:
    runs-on: self-hosted
    steps:
    - name: Hello
      run: |
        sleep 60
        echo "Hello world!"
